### ISSUE TITLE
Provide some default video metrics

### ISSUE THREAD

**Issue by cdthompson** [veeta-tv/roku-gamp#19]
This library operates at a fairly low level, exposing function calls which map directly to the measurement protocol types.  It could be more helpful in providing some basic roVideoPlayer and \<Video\> node integration for gathering video playback metrics.  

http://www.charlesfarina.com/video-tracking-google-analytics/ has a good suggestion of how to model this.

**Comment by welcome-systems** [comment]
Any plans for implementing Timing Tracking? That could potentially be used for send the load/buffer times for videos. Most roku apps are video apps, so some support for video analytics makes this even more relevant (without this not sure how to get to the nice reports in the link/article give  above).

**Comment by welcome-systems** [comment]
Implemented Timing. May be useful for other.

googleAnalytics.brs:
---------------------
near line 233:

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
' Use the Timing to measure periods of time. This is used to measure page or video load 
' times. 
'
' | Parameter       | Value Type  | Default Value | Max Length
' -----------------------------------------------------------
' | category        | text        | None          | 150 Bytes
' | variable        | text        | None          | 500 Bytes
' | time            | integer     | None          | None
' | label           | text        | None          | 500 Bytes
'
' XXX :  Added by Sridhar Guthula
Function gamobileTiming(category As String, variable As String, time As String, label="" As String) As Void
  if m.gamobile.debug
    ? "[GA] Timing: " + category + "/" + variable
  end if

  hit_params = {
    t: "timing"
    utc: URLEncode(category)   ' EUser timing category. Required
    utv: URLEncode(variable)   ' User timing variable name. Required.
    utt: URLEncode(time)       ' User timing time. Required.
  }
  if label <> "" then hit_params.utl = URLEncode(label)      ' User timing label.
  gamobileSendHit(hit_params)  
End Function


GampTask.xml
---------------
near line 63: 
  m.top.observeField("timing", port)

near line 107:
      else if field = "timing" then
        if data.category = invalid then data.category = ""
        if data.variable = invalid then data.variable = ""
        if data.time = invalid then data.time = ""
        if data.label = invalid then data.label = ""
        gamobileTiming(data.category, data.variable, data.time, data.label)
      end if

near line 182:
    
    <field id="timing" type="assocarray"/>

**Comment by cdthompson** [comment]
thanks for the effort.  can you put this in a pull request?

**Comment by cdthompson** [comment]
Closing.  No further improvements to this library since Roku announced native support for google analytics
