### ISSUE TITLE
Events not getting generated with "value" specified.

### ISSUE THREAD

**Issue by welcome-systems** [veeta-tv/roku-gamp#21]
I removed "value" from my code as including this stopped events from getting generated.  

Upon further investigation, found the "value" has to be an integer and I was sending a URL. So, may be good to mention that in the doc or in the comments around the "event" source code (will save other developers some time).

**Comment by cdthompson** [comment]
Added parameter documentation to the function descriptions.

**Comment by welcome-systems** [comment]
Wow... this documentation looks nice. Makes it a lot more easy.
