### ISSUE TITLE
triggering screenView right after setting control to "Run" doesn't fire

### ISSUE THREAD

**Issue by tkiethanom** [veeta-tv/roku-gamp#22]
m.gampTask = m.top.findNode("GampTask")    
m.gampTask.control = "RUN"        
m.gampTask.screenView = { screenName: "HomeScreen" } 

Doing these in this order doesn't fire the screenView. I'm assuming because the enabling of the GampTask component is happening asynchronously? The screenView is trying to trigger before the component is enabled.

**Comment by ghost** [comment]
You're absolutely right, thanks for pointing this out.  I've run across this problem myself with other long-running tasks.

My solution in those cases was to add an interface field "ready" to the task which is set by the execFunction.  Then the app waits for all these long-running tasks to be "ready" before it begins normal app functioning.  

The alternative is to rearchitect the execFunction to be a one-shot report and exit.  There are pros and cons to each architecture.  

For now, I can add an example of the "ready" field in the sources here.

**Comment by cdthompson** [comment]
"ready" field and example usage added in https://github.com/veeta-tv/roku-gamp/commit/4267ccd996923236325d25fab63ce4bfae3b2a47
