### ISSUE TITLE
Not really an issue, but I see what your problem is....

### ISSUE THREAD

**Issue by silentpickle** [veeta-tv/roku-gamp#3]
response = request.PostFromString(full_params)

Async doesn't work because the request leaves scope before the request itself actually completes.   Your request gets garbage collected before it goes out the door.

You can store that request in a global object somewhere, if you do one request at a time.

**Comment by cdthompson** [comment]
Thanks!  The code needs some updating... I think doing the request synchronously keeps the library simple and usable.  I'll remove the comments for now, though I'm open to someone submitting a pull request with added async functionality.

**Comment by cdthompson** [comment]
Removed the comments in https://github.com/veeta-tv/roku-gamp/commit/7a5257cdd97b9d9cf70f92c80e4fc411ca0e6a52

Thanks for the review and feedback!
